void square_functions(int num, int type, int color, int incolor, char sym, COORD cord);
void drawing(int x, int y, int color, char sym);
void numbers_functions(int num, int type, int color, char sym, COORD cord);
void alphabets_functions(int num, int type, int color, char sym, COORD cord);
void rectangle_functions(int num, int type, int color, int incolor, char sym, COORD cord);
void parallelogram_functions(int num, int type, int color, int incolor, char sym, COORD cord);
void trapezium_functions(int num, int type, int color, int incolor, char sym, COORD cord);
void diamond_functions(int num, int type, int color, int incolor, char sym, COORD cord);
void hexagon_functions(int num, int type, int color, int incolor, char sym, COORD cord);
void pentagon_functions(int num, int type, int color, int incolor, char sym, COORD cord);
void line_functions(int num, int type, int color,  char sym, COORD cord);
void inverted_triangle_functions(int num, int type, int color, int incolor, char sym, COORD cord);
void mirror_triangle_functions(int num, int type, int color, int incolor, char sym, COORD cord);
void simple_triangle_functions(int num, int type, int color, int incolor, char sym, COORD cord);
void up_arrow_functions(int num, int type, int color, int incolor, char sym, COORD cord);
void down_arrow_functions(int num, int type, int color, int incolor, char sym, COORD cord);
void inverted_mirror_triangle_functions(int num, int type, int color, int incolor, char sym, COORD cord);
void chatbox(int num,char sym, int color, COORD cord);
